In [1]:
import numpy as np 

In [2]:
my_1d_array = np.random.randint(2,8,16) # 16 random numbers between 2 and 8.

In [3]:
np.max(my_1d_array) #Max is "7. 

7

In [4]:
my_1d_array.max() #Same result - This is better to do, as you can specify max in rows and columns

7

In [5]:
my_1d_array.min()


2

In [6]:
my_1d_array.mean()

4.75

In [7]:
my_1d_array.sum()

76

In [8]:
my_1d_array.std()

1.4361406616345072

In [9]:
#Multidimensional arrays

my_2d_array = my_1d_array.reshape(4,4)

In [10]:
print(my_2d_array)

[[5 6 7 2]
 [7 4 4 4]
 [4 6 5 3]
 [3 6 4 6]]


In [11]:
my_2d_array.max()

7

In [12]:
my_2d_array.max(axis=0) #Maximum value for each column

array([7, 6, 7, 6])

In [14]:
my_2d_array.max(axis=1) #Maximum value for each row

array([7, 7, 6, 6])

In [15]:
#We can use arg max and arg minimum - to find the index of the element that has either of these

my_2d_array.argmax(axis=0) #Tells us index position in column

array([1, 0, 0, 3], dtype=int64)

In [16]:
my_2d_array.argmax(axis=1) #Tells us index position in row

array([2, 0, 1, 1], dtype=int64)

In [18]:
np.sort(my_1d_array) #Sort array in ascending order


array([2, 3, 3, 4, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7])

In [19]:
a = np.array([1,2,3,4,5])

In [20]:
a + 10 #Numpy has added 10 to each of the elements here

array([11, 12, 13, 14, 15])

In [23]:
a-10


array([-9, -8, -7, -6, -5])

In [24]:
a*10


array([10, 20, 30, 40, 50])

In [25]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [26]:
b = np.array([3,7,1,2,6])

a+b #It has added each "a" element to each "b" elements here

array([ 4,  9,  4,  6, 11])

In [27]:
a = np.array([-2,-1,0,1,2])
#You can square all numbers
np.square(a)

array([4, 1, 0, 1, 4])

In [28]:
np.sqrt(a) #There are some nan - not a number - can't take square root of negative numbers

C:\Users\19144\AppData\Local\Temp\ipykernel_24828\2835837605.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([       nan,        nan, 0.        , 1.        , 1.41421356])

In [29]:
np.sign(a) #Returns -1 for all negative numbers, 1 for all positive numbers

array([-1, -1,  0,  1,  1])

In [30]:
np.sin(a)

array([-0.90929743, -0.84147098,  0.        ,  0.84147098,  0.90929743])

In [31]:
np.cos(a)

array([-0.41614684,  0.54030231,  1.        ,  0.54030231, -0.41614684])

In [32]:
np.tan(a)

array([ 2.18503986, -1.55740772,  0.        ,  1.55740772, -2.18503986])

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.dot(a,b) #1*4 + 2*5 + 3*6 = 

32